CREATE TYPE "UserRole" AS ENUM ('ADMIN', 'SUPER_ADMIN');

ALTER TABLE "User"
ADD COLUMN "role" "UserRole" NOT NULL DEFAULT 'ADMIN',
ADD COLUMN "permissions" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "isActive" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "HeroPhone" ADD COLUMN "episodeId" INTEGER;

ALTER TABLE "HeroPhone"
ADD CONSTRAINT "HeroPhone_episodeId_fkey"
FOREIGN KEY ("episodeId") REFERENCES "Episode"("id") ON DELETE CASCADE ON UPDATE CASCADE;

CREATE INDEX "HeroPhone_episode_active_idx" ON "HeroPhone"("episodeId", "isActive");
